### ISSUE TITLE
how configure the ngnix server for leverage browser caching

### ISSUE THREAD

**Issue by inyee786** [tiangolo/angular-docker-multi-stage-example#1]
```
server {
   listen 80;
   location / {
   root /usr/share/nginx/html;
   index index.html index.htm;
   try_files $uri $uri/ /index.html =404;
   }
   location ~*  \.(jpg|jpeg|png|gif|ico|css|js)$ {
       expires 365d;
   }
}
```
i have raised issue on stackoverflow "https://stackoverflow.com/questions/48462999/how-to-write-nginx-conf-file-for-angular-app-with-leverage-browser"

**Comment by tiangolo** [comment]
And did that work? Did the unmodified instructions work?

**Comment by inyee786** [comment]
no it's not working.
i am getting blank screen and in console i am getting
this warning
https://i.stack.imgur.com/LoGw6.png

**Comment by tiangolo** [comment]
Did the unmodified / original instructions work?

**Comment by inyee786** [comment]
yes the original instruction is working

but  i want leverage browser caching in my app

which can be achieve by

```
 location ~*  \.(jpg|jpeg|png|gif|ico|css|js)$ {
       expires 365d;
   }
```

**Comment by inyee786** [comment]
i am checking the gtmetrix for my app and it is very bad
![screenshot from 2018-02-07 22-24-25](https://user-images.githubusercontent.com/20504600/35929540-b9fb7124-0c55-11e8-8850-b69e821693f6.png)

**Comment by tiangolo** [comment]
I'm sorry, I don't know what "gtmetrix" is.

**Comment by inyee786** [comment]
I got the solution, 
And gtmetrix is a tool that tell us the performance of your website just like Google page speed

**Comment by inyee786** [comment]
Thank u, for you'r help
